# Generated by Django 4.0 on 2024-03-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_CREATE_TABLES_UserAccount_Post_Category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='post.Category'),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
