# Generated by Django 5.0.2 on 2024-02-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_created_at_post_is_actual_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='post 74', max_length=128, null=True),
        ),
    ]
